Repository thefrontside/effection, pull requests merged in 2022-01, with the labels that each got.

#610 Publish New Versions
  .changes/fetch.md
  packages/atom/CHANGELOG.md
  packages/atom/package.json
  packages/dispatch/CHANGELOG.md
  packages/dispatch/package.json
  packages/duplex-channel/CHANGELOG.md
  packages/duplex-channel/package.json
  packages/effection/CHANGELOG.md
  packages/effection/package.json
  packages/fetch/CHANGELOG.md
  packages/fetch/package.json
  packages/inspect-server/CHANGELOG.md
  packages/inspect-server/package.json
  packages/inspect-ui/CHANGELOG.md
  packages/inspect-ui/package.json
  packages/inspect-utils/CHANGELOG.md
  packages/inspect-utils/package.json
  packages/inspect/CHANGELOG.md
  packages/inspect/package.json
  packages/mocha/CHANGELOG.md
  packages/mocha/package.json
  packages/process/CHANGELOG.md
  packages/process/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/websocket-client/CHANGELOG.md
  packages/websocket-client/package.json
  packages/websocket-server/CHANGELOG.md
  packages/websocket-server/package.json
Labels: version updates

#600 add OperationObject and `toOperation` method
  .changes/add-operation-object.md
  packages/core/src/controller/controller.ts
  packages/core/src/controller/delegate-controller.ts
  packages/core/src/index.ts
  packages/core/src/labels.ts
  packages/core/src/operation.ts
  packages/core/src/predicates.ts
  packages/core/src/symbol.ts
  packages/core/src/task.ts
  packages/core/test/labels.test.ts
  packages/fetch/test/fetch.test.ts
  packages/inspect-server/package.json
  packages/inspect-ui/package.json
  packages/inspect-utils/package.json
  packages/main/src/browser.ts
  packages/main/src/node.ts
  packages/process/test/exec.test.ts
  yarn.lock
Labels: preview

#616 Add testing guide for Jest and Mocha
  website/docs/guides/testing.md
Labels: documentation
